/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SplatRouteImport } from './routes/$'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as TSlugRouteImport } from './routes/t/$slug'
import { Route as ShareTokenRouteImport } from './routes/share/$token'
import { Route as DashboardAdminRouteImport } from './routes/dashboard/admin'
import { Route as AuthConfirmRouteImport } from './routes/auth/confirm'
import { Route as TreesTreeIdRouteRouteImport } from './routes/trees/$treeId/route'
import { Route as TreesTreeIdIndexRouteImport } from './routes/trees/$treeId/index'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const TSlugRoute = TSlugRouteImport.update({
  id: '/t/$slug',
  path: '/t/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AuthConfirmRoute = AuthConfirmRouteImport.update({
  id: '/auth/confirm',
  path: '/auth/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const TreesTreeIdRouteRoute = TreesTreeIdRouteRouteImport.update({
  id: '/trees/$treeId',
  path: '/trees/$treeId',
  getParentRoute: () => rootRouteImport,
} as any)
const TreesTreeIdIndexRoute = TreesTreeIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TreesTreeIdRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/trees/$treeId': typeof TreesTreeIdRouteRouteWithChildren
  '/auth/confirm': typeof AuthConfirmRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/share/$token': typeof ShareTokenRoute
  '/t/$slug': typeof TSlugRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/trees/$treeId/': typeof TreesTreeIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/share/$token': typeof ShareTokenRoute
  '/t/$slug': typeof TSlugRoute
  '/dashboard': typeof DashboardIndexRoute
  '/trees/$treeId': typeof TreesTreeIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/trees/$treeId': typeof TreesTreeIdRouteRouteWithChildren
  '/auth/confirm': typeof AuthConfirmRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/share/$token': typeof ShareTokenRoute
  '/t/$slug': typeof TSlugRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/trees/$treeId/': typeof TreesTreeIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/$'
    | '/login'
    | '/register'
    | '/trees/$treeId'
    | '/auth/confirm'
    | '/dashboard/admin'
    | '/share/$token'
    | '/t/$slug'
    | '/dashboard/'
    | '/trees/$treeId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/login'
    | '/register'
    | '/auth/confirm'
    | '/dashboard/admin'
    | '/share/$token'
    | '/t/$slug'
    | '/dashboard'
    | '/trees/$treeId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/$'
    | '/login'
    | '/register'
    | '/trees/$treeId'
    | '/auth/confirm'
    | '/dashboard/admin'
    | '/share/$token'
    | '/t/$slug'
    | '/dashboard/'
    | '/trees/$treeId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  SplatRoute: typeof SplatRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  TreesTreeIdRouteRoute: typeof TreesTreeIdRouteRouteWithChildren
  AuthConfirmRoute: typeof AuthConfirmRoute
  ShareTokenRoute: typeof ShareTokenRoute
  TSlugRoute: typeof TSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/t/$slug': {
      id: '/t/$slug'
      path: '/t/$slug'
      fullPath: '/t/$slug'
      preLoaderRoute: typeof TSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$token': {
      id: '/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/auth/confirm': {
      id: '/auth/confirm'
      path: '/auth/confirm'
      fullPath: '/auth/confirm'
      preLoaderRoute: typeof AuthConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trees/$treeId': {
      id: '/trees/$treeId'
      path: '/trees/$treeId'
      fullPath: '/trees/$treeId'
      preLoaderRoute: typeof TreesTreeIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trees/$treeId/': {
      id: '/trees/$treeId/'
      path: '/'
      fullPath: '/trees/$treeId/'
      preLoaderRoute: typeof TreesTreeIdIndexRouteImport
      parentRoute: typeof TreesTreeIdRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardAdminRoute: typeof DashboardAdminRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardAdminRoute: DashboardAdminRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface TreesTreeIdRouteRouteChildren {
  TreesTreeIdIndexRoute: typeof TreesTreeIdIndexRoute
}

const TreesTreeIdRouteRouteChildren: TreesTreeIdRouteRouteChildren = {
  TreesTreeIdIndexRoute: TreesTreeIdIndexRoute,
}

const TreesTreeIdRouteRouteWithChildren =
  TreesTreeIdRouteRoute._addFileChildren(TreesTreeIdRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  SplatRoute: SplatRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  TreesTreeIdRouteRoute: TreesTreeIdRouteRouteWithChildren,
  AuthConfirmRoute: AuthConfirmRoute,
  ShareTokenRoute: ShareTokenRoute,
  TSlugRoute: TSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
